export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_CATS_PENDING = 'REQUEST_CATS_PENDING';
export const REQUEST_CATS_SUCCESS = 'REQUEST_CATS_SUCCESS';
export const REQUEST_CATS_FAIL = 'REQUEST_CATS_FAIL';